import Head from "next/head";
import SalesforceConnectButton from "@/components/SalesforceConnectButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center flex-col gap-2 items-center">
          <h1 className="text-3xl font-bold">AI salesbridge</h1>
          <SalesforceConnectButton />
        </div>
      </main>
    </>
  );
}
